"""Multi-scene renderer used by the Faceless Forge production endpoint.

The regular Render Studio is intentionally generic.  This module turns a Forge
blueprint into a coherent vertical video: it creates one visual and voice clip
per scene, gives stills a subtle camera move, concatenates the scenes, and then
burns captions using the real TTS durations.
"""
import math
import re
import uuid
from pathlib import Path
from typing import Any

import ai_engine
from media_store import MEDIA_DIR, get_duration, media_url, new_media_path, run_ffmpeg
from pipelines import render_worker
from stt_engine import segments_to_srt
from tts_engine import edge_generate


MAX_SCENES = 6
_RESOLUTION_RE = re.compile(r"^(?P<width>[1-9]\d{2,3})x(?P<height>[1-9]\d{2,3})$")


def prepare_scenes(shots: list[dict[str, Any]], concept: str = "") -> list[dict[str, str]]:
    """Return a small, safe production plan from a generated blueprint.

    A six-scene ceiling keeps a single web job predictable in time and image
    cost.  Blueprint fields are generated by an LLM, so this function also
    supplies useful fallbacks rather than passing blank prompts to providers.
    """
    scenes: list[dict[str, str]] = []
    for position, raw_shot in enumerate(shots[:MAX_SCENES], start=1):
        if not isinstance(raw_shot, dict):
            continue
        narration = str(raw_shot.get("narration") or raw_shot.get("on_screen_text") or "").strip()
        if not narration:
            continue
        prompt = str(raw_shot.get("image_prompt") or raw_shot.get("visual") or "").strip()
        if not prompt:
            prompt = (
                f"Vertical 9:16 cinematic editorial visual for scene {position} about {concept or narration}. "
                "No readable text, clear central subject, detailed lighting, premium documentary style."
            )
        scenes.append({
            "label": str(raw_shot.get("label") or f"Cảnh {position}").strip()[:80],
            "narration": narration[:900],
            "image_prompt": prompt[:1800],
        })
    return scenes


def _parse_resolution(resolution: str) -> tuple[int, int]:
    match = _RESOLUTION_RE.fullmatch(resolution or "")
    if not match:
        raise ValueError("Độ phân giải phải có dạng 1080x1920")
    width, height = int(match.group("width")), int(match.group("height"))
    if width * height > 4_500_000:
        raise ValueError("Độ phân giải quá lớn cho một job dựng video web")
    return width, height


def _concat_manifest(paths: list[Path], prefix: str) -> Path:
    """Write an ffmpeg concat manifest for internal, generated media files."""
    manifest = MEDIA_DIR / "renders" / f"{prefix}_{uuid.uuid4().hex[:12]}.txt"
    lines = []
    for path in paths:
        # Paths are generated internally and never include a user-provided quote.
        escaped = str(path.resolve()).replace("'", "'\\''")
        lines.append(f"file '{escaped}'")
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return manifest


async def _render_scene(image_path: Path, audio_path: Path, out_path: Path,
                        width: int, height: int) -> None:
    """Render a portrait scene with a restrained Ken Burns movement."""
    # A single zoompan frame per input frame avoids a static slideshow while
    # keeping render time low enough for a hosted background job.
    visual_filter = (
        f"scale={width}:{height}:force_original_aspect_ratio=increase,"
        f"crop={width}:{height},"
        f"zoompan=z='min(zoom+0.00055,1.075)':"
        f"x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:"
        f"s={width}x{height}:fps=30,setsar=1"
    )
    await run_ffmpeg([
        "-framerate", "30", "-loop", "1", "-i", str(image_path),
        "-i", str(audio_path), "-vf", visual_filter,
        "-map", "0:v:0", "-map", "1:a:0",
        "-c:v", "libx264", "-preset", "veryfast", "-tune", "stillimage",
        "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k",
        "-movflags", "+faststart", "-shortest", str(out_path),
    ], timeout=1800)


async def render_multiscene_video(progress_cb, *, shots: list[dict[str, Any]],
                                  concept: str, voice: str, image_model: str,
                                  resolution: str) -> dict[str, Any]:
    """Create a captioned multi-scene Faceless Forge video in a background job."""
    scenes = prepare_scenes(shots, concept)
    if not scenes:
        raise RuntimeError("Blueprint chưa có cảnh hợp lệ để dựng video")
    if image_model not in ai_engine.IMAGE_MODELS:
        raise RuntimeError("Model ảnh không hợp lệ")

    width, height = _parse_resolution(resolution)
    audio_paths: list[Path] = []
    segment_paths: list[Path] = []
    visual_urls: list[str] = []
    subtitle_segments: list[dict[str, Any]] = []
    timeline = 0.0
    scene_count = len(scenes)

    await progress_cb(4, f"Đang chuẩn bị {scene_count} cảnh video dọc...")
    for index, scene in enumerate(scenes, start=1):
        scene_base = 7 + int((index - 1) * 62 / scene_count)
        await progress_cb(scene_base, f"Đang tạo visual cảnh {index}/{scene_count}...")
        images = await ai_engine.generate_images(scene["image_prompt"], image_model, 1)
        if not images:
            raise RuntimeError(f"Không tạo được visual cho cảnh {index}")
        image = images[0]
        image_path = MEDIA_DIR / "images" / str(image["filename"])
        if not image_path.is_file():
            raise RuntimeError(f"Không tìm thấy visual đã tạo cho cảnh {index}")
        visual_urls.append(str(image.get("url") or media_url(image_path)))

        await progress_cb(scene_base + 10, f"Đang tạo voice-over cảnh {index}/{scene_count}...")
        audio_path = new_media_path("tts", "mp3", "forge_scene_")
        await edge_generate(scene["narration"], voice, out_path=audio_path)
        duration = max(0.5, await get_duration(audio_path))
        audio_paths.append(audio_path)

        await progress_cb(scene_base + 16, f"Đang dựng chuyển động cảnh {index}/{scene_count}...")
        segment_path = new_media_path("renders", "mp4", "forge_scene_")
        await _render_scene(image_path, audio_path, segment_path, width, height)
        segment_paths.append(segment_path)
        subtitle_segments.append({
            "start": timeline,
            "end": timeline + duration,
            "text": scene["narration"],
        })
        timeline += duration

    await progress_cb(72, "Đang ghép các cảnh thành một câu chuyện...")
    video_manifest = _concat_manifest(segment_paths, "forge_video")
    stitched_video = new_media_path("renders", "mp4", "forge_story_")
    await run_ffmpeg([
        "-f", "concat", "-safe", "0", "-i", str(video_manifest),
        "-c", "copy", "-movflags", "+faststart", str(stitched_video),
    ], timeout=1800)

    await progress_cb(79, "Đang ghép voice-over hoàn chỉnh...")
    audio_manifest = _concat_manifest(audio_paths, "forge_audio")
    full_audio = new_media_path("tts", "mp3", "forge_voiceover_")
    await run_ffmpeg([
        "-f", "concat", "-safe", "0", "-i", str(audio_manifest),
        "-c", "copy", str(full_audio),
    ], timeout=600)

    srt_content = segments_to_srt(subtitle_segments)

    async def final_render_progress(percent: int, message: str):
        await progress_cb(82 + int(max(0, min(100, percent)) * 0.15), message)

    await progress_cb(82, "Đang căn phụ đề theo lời đọc và xuất MP4...")
    final = await render_worker(
        final_render_progress, video_path=stitched_video, srt_content=srt_content,
        resolution=f"{width}x{height}",
    )
    await progress_cb(99, "Đang đóng gói video và voice-over để tải xuống...")
    return {
        "video_url": final["video_url"],
        "audio_url": media_url(full_audio),
        "duration": round(max(0.0, float(final.get("duration") or timeline)), 2),
        "scene_count": scene_count,
        "image_urls": visual_urls,
        "srt": srt_content,
    }
